### ISSUE TITLE
Delete data webhook in production server

### ISSUE THREAD

**Issue by stevedj** [jverce/salesforce-webhooks#18]
Hi @jverce thank you for your plugin,

Just wondering if we delete the apex triggers in production, 
using [deleteWebhook](https://github.com/jverce/salesforce-webhooks#webhook-deletion), do we need to change the status from "active" to "deleted"? [link](https://help.salesforce.com/s/articleView?id=000385617&type=1)

Cheers!

**Comment by jverce** [comment]
Hi @stevedj, sorry for the delay (Github notifications are too noisy and this one fell through the cracks).

When calling `deleteWebhook`, the library will attempt a deletion of the resources created by the library itself by following a specific sequence of steps. Since the resources created by the library are named randomly (to avoid name collisions), the proper way of dealing with this is to store the information returned by the `createWebhook` methods so that it can be fed back to the `deleteWebhook` method. The latter will delete the specified resources entirely, not just disable them (keeping Apex code around consumes resources since Salesforce has a limit on the amount of code that it hosts).

The information passed to a `deleteWebhook` method will look something like this:
```json
{
  "remoteSiteName": "SW_Endpoint_d34b640b2ab3e60ec1b47457733b",
  "classNames": [
    "SW_SObjectFactory_c9038f73cd7062d5bd9845",
    "SW_Callout_4326701c9c6f9300168dfed9d566",
    "SW_CalloutMock_d90f83dbf0a5f91850aa6b40",
    "SW_Test_35d1a6e66a4966d9c5de76e2f7f25c33"
  ],
  "triggerNames": [
    "SW_Trigger_ac2b6295cfddae0d279257e596e2"
  ]
}
```

The method will effectively delete those resources via a SOAP API request using a [payload](https://github.com/jverce/salesforce-webhooks/blob/master/resources/templates/soap/apex/DeleteApexCode.xml.handlebars) that looks something like this:
```handlebars
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <env:Header>
        <urn:SessionHeader xmlns:urn="http://soap.sforce.com/2006/08/apex">
            <urn:sessionId>{{authToken}}</urn:sessionId>
        </urn:SessionHeader>
    </env:Header>
    <env:Body>
        <compileAndTest xmlns="http://soap.sforce.com/2006/08/apex">
            <CompileAndTestRequest>
                {{#each classNames}}
                <deleteClasses>{{this}}</deleteClasses>
                {{/each}}

                {{#each triggerNames}}
                <deleteTriggers>{{this}}</deleteTriggers>
                {{/each}}
            </CompileAndTestRequest>
        </compileAndTest>
    </env:Body>
</env:Envelope>
```

If you're not getting the expected behaviour, could you provide more information? In particular, this would be useful:
1. The response you're getting from Salesforce when creating the webhook
2. The value that the library returns after creating the webhook
3. The value that the library returns after (attempting to) delete the webhook
4. Any error messages and/or stack traces that you get

Thanks!
